version: '3.7'

services:
  url-shortener-backend:
    build:
      context: url-shortener-backend
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
  db:
    image: mongo:4.2.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb_data_container: